 ## array and how to create array

In [26]:
import numpy as np       # one dimenssion array
a=np.array([5,5,5])
a

array([5, 5, 5])

In [12]:
a[1]     # indexing

5

In [13]:
a[0]

5

In [14]:
a[0:]

array([5, 5, 5])

In [2]:
type(a)         # nd array   having any dimenssion
                 # one dimenssion array is called vector

numpy.ndarray

In [6]:
b= np.array([[5,5,5,5,5],[5,5,5,5,5]])   # two dimenssion array called matrix
b

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [7]:
c=np.array([[3,3,3,3],[3,3,3,3],[3,3,3,3]])
c

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [8]:
type(c)

numpy.ndarray

In [9]:
len(c)

3

In [15]:
z=np.array([1,2,3,4,5])
z

array([1, 2, 3, 4, 5])

In [17]:
x=np.zeros(2)     # zero array
x

array([0., 0.])

In [19]:
f=np.ones(4)     # ones array
f

array([1., 1., 1., 1.])

In [21]:
d=np.empty(3)
d

array([7.96899553e-312, 0.00000000e+000, 5.37653783e+173])

## how to craete array

In [28]:
# range of element
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [29]:
# specific range of elements
s=np.arange(2,20)
s

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [30]:
# continue
f=np.arange(3,30,3)
f

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [31]:
# linear spaced array
h=np.linspace(0,10,num=5) # give use 5 num
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
# specific data types in array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [33]:
j=np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

In [34]:
k=np.zeros((3,4))    # 2D arrays
k

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
l=np.zeros((4,5))      # 4 coloums 4 rows
l

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
o=np.zeros((6,7))      # 6 coloums and 7 rows
o

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## 3D aaray

In [39]:
# making and reshaping of 3D aaray    # 2 matrices 4 colums  3 rows
v=np.arange(24).reshape(2,3,4)
v

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])