## numpy practice session

In [1]:
# pip install numpy

In [2]:
# import libarary
import numpy as np


## creating array using numpy

In [3]:
food=np.array(["pakora","samosa","roll"])
food

array(['pakora', 'samosa', 'roll'], dtype='<U6')

In [4]:
type(food)

numpy.ndarray

In [5]:
len(food)

3

In [6]:
food[2]

'roll'

In [7]:
food[1]

'samosa'

In [8]:
food[0]

'pakora'

In [9]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [10]:
type(price)

numpy.ndarray

In [11]:
len(price)

3

In [12]:
price[2]

5

In [13]:
price[0]

5

In [14]:
price.mean()

5.0

In [15]:
# zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
# ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# table of 5  # last value is exlusive
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
# line space
np.linspace(1,15, num=5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [23]:
# specify data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [24]:
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array function

In [26]:
a=np.array([2,3,2,5,6,10.5,2.2])
a

array([ 2. ,  3. ,  2. ,  5. ,  6. , 10.5,  2.2])

In [27]:
a.sort()
a

array([ 2. ,  2. ,  2.2,  3. ,  5. ,  6. , 10.5])

In [28]:
a.argmax
a

array([ 2. ,  2. ,  2.2,  3. ,  5. ,  6. , 10.5])

In [29]:
a.compress
a

array([ 2. ,  2. ,  2.2,  3. ,  5. ,  6. , 10.5])

In [30]:
a.argpartition
a

array([ 2. ,  2. ,  2.2,  3. ,  5. ,  6. , 10.5])

In [31]:
b=np.array([5,3,7,2,10.6,9,4])
b

array([ 5. ,  3. ,  7. ,  2. , 10.6,  9. ,  4. ])

In [32]:
np.concatenate((a,b))

array([ 2. ,  2. ,  2.2,  3. ,  5. ,  6. , 10.5,  5. ,  3. ,  7. ,  2. ,
       10.6,  9. ,  4. ])

In [34]:
c=np.concatenate((a,b))
c

array([ 2. ,  2. ,  2.2,  3. ,  5. ,  6. , 10.5,  5. ,  3. ,  7. ,  2. ,
       10.6,  9. ,  4. ])

In [37]:
c.sort()
c

array([ 2. ,  2. ,  2. ,  2.2,  3. ,  3. ,  4. ,  5. ,  5. ,  6. ,  7. ,
        9. , 10.5, 10.6])

In [ ]:
# 2-D array


In [5]:
a=np.array([[2,4,6,7],[7,9,2,1]])
a

array([[2, 4, 6, 7],
       [7, 9, 2, 1]])

In [6]:
import numpy as np
b=np.array([[7,8,3,1],[8,4,3,6]])
b

array([[7, 8, 3, 1],
       [8, 4, 3, 6]])

In [7]:
c=np.concatenate((a,b), axis=0)
c

array([[2, 4, 6, 7],
       [7, 9, 2, 1],
       [7, 8, 3, 1],
       [8, 4, 3, 6]])

In [8]:
c=np.concatenate((a,b), axis=1)
c

array([[2, 4, 6, 7, 7, 8, 3, 1],
       [7, 9, 2, 1, 8, 4, 3, 6]])

In [ ]:
# 3-D array

In [10]:
a=np.array([[[2,3,4],
            [4,5,6]],
           [[4,6,7]
           ,[1,4,2]],
           [[2,5,7],
           [5,3,5]]])
a

array([[[2, 3, 4],
        [4, 5, 6]],

       [[4, 6, 7],
        [1, 4, 2]],

       [[2, 5, 7],
        [5, 3, 5]]])

In [12]:
# to find the number of dimension
a.ndim

3

In [18]:
a.size

18

In [15]:
b=np.array([[3,4,5],
            [3,6,7],
            [7,2,6]])
b

array([[3, 4, 5],
       [3, 6, 7],
       [7, 2, 6]])

In [16]:
b.ndim

2

In [17]:
# size of array
b.size

9

In [19]:
#shape
a.shape

(3, 2, 3)

In [20]:
b.shape

(3, 3)

In [36]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [41]:
c=a.reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
# reshape
np.reshape(a,newshape=(1,6),order='c')

array([[0, 1, 2, 3, 4, 5]])

In [45]:
# convert 1D to 2D ROW WISE
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [46]:
a.shape

(6,)

In [47]:
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6]])

In [48]:
b.shape

(1, 6)

In [49]:
# colum wise 2D
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
a=np.array([2,3,5,7,4,9,6])
a.sort()
a

array([2, 3, 4, 5, 6, 7, 9])

In [62]:
# slicing
a[2:9]


array([4, 5, 6, 7, 9])

In [63]:
a*6   # multiplication

array([12, 18, 24, 30, 36, 42, 54])

In [64]:
a.sum()   #addition

36

In [65]:
a.mean()

5.142857142857143